### ISSUE TITLE
(frontend) add link to alternative signup/login

### ISSUE THREAD

**Issue by JacksonNace** [casanccs/projectHunter#24]
add a "Already have an account? Log in here" and a "Don't have an account? Register here" that takes you to alternative pages
(phrases can definitely be changed out those are examples)

**Comment by Sky-De** [comment]
@JacksonNace hi, i would like to address this issue,
Please assign this to me
Thanks

**Comment by Sky-De** [comment]
@JacksonNace Upon opening the app, it directs me to the login page which is not ideal. Can I submit a request to fix this? 

![chrome-capture-2024-1-5 (1)](https://github.com/casanccs/projectHunter/assets/79264045/8d81a8b7-6376-4563-9bfd-67f298f7ee1d)

**Comment by Sky-De** [comment]
@JacksonNace hi again, as we are done with this issue please mark this issue as solved
thanks
